### ISSUE TITLE
This should be const function, since it's not modifying the state of class.

### ISSUE THREAD

**Issue by SteelPh0enix** [jakub-gonet/fan_meter#1]
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/adc.hpp#L27

It's possible that when const'ed, it would inline automatically.

**Comment by SteelPh0enix** [comment]
Same applies to
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/pins.hpp#L20

**Comment by jgonet** [comment]
Resolved by:
https://github.com/jakub-gonet/fan_meter/commit/047611639dd783f03685e726908cb879369c4e78
https://github.com/jakub-gonet/fan_meter/commit/fc08d1a7c38e2d6a43fc26c72908f944fb7a8af2
