### ISSUE TITLE
F_CPU should be normally passed as argument

### ISSUE THREAD

**Issue by SteelPh0enix** [jakub-gonet/fan_meter#2]
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/main.cpp#L7

Add -DF_CPU 1000000 to compilation command (avr-gcc step), instead of hard-coding it.

**Comment by jgonet** [comment]
Resolved by:
https://github.com/jakub-gonet/fan_meter/commit/0d1e064627fa32b621a79aff6406a813a49bc12c
