### ISSUE TITLE
Getters and setters instead of raw fields

### ISSUE THREAD

**Issue by SteelPh0enix** [jakub-gonet/fan_meter#3]
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/measure.hpp#L13

https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/measure.hpp#L19

I would recommend making those as private fields, with getters/setters, in case of any future change to the interface. There shouldn't be any performance issues, but i'm not 100% sure about that.

**Comment by jgonet** [comment]
Resolved by:
https://github.com/jakub-gonet/fan_meter/commit/510e6be2ebacce7bb1b75f6608b80a1a1dfe5cab
https://github.com/jakub-gonet/fan_meter/commit/8d74308aa71b72fe8a46c423d430a64a8e4ce981
