### ISSUE TITLE
Use static_cast<>() instead of C-style cast

### ISSUE THREAD

**Issue by SteelPh0enix** [jakub-gonet/fan_meter#4]
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/measure.cpp#L53
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/measure.cpp#L58

**Comment by jgonet** [comment]
Resolved by:
https://github.com/jakub-gonet/fan_meter/commit/a63b4d1fd8e279b8ce26e4bda7c1da44f61b9b43
