### ISSUE TITLE
Make a function returning the value instead

### ISSUE THREAD

**Issue by SteelPh0enix** [jakub-gonet/fan_meter#5]
https://github.com/jakub-gonet/fan_meter/blob/f7c85646b588f5136160df8abf24a31ece974b69/src/pwm.hpp#L13

Making a function *probably* could be a little better solution, instead of field (look up the getter/setter issue)

**Comment by jgonet** [comment]
Resolved by:
https://github.com/jakub-gonet/fan_meter/commit/6b6fe7f5826fd983851071e0fdccaf92a9feedce
